# numpy

## Basicas de numpy

In [16]:
import numpy as np
import math

Creamos arrays

In [22]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([20,20,30])
arr4 = np.array([20,30,40,50])

In [18]:
print(arr2)

[ 4.  9. 16.]
[20 20 30]


Imprimimos el array y vemos el tipo de dato

In [21]:
arr3 = np.array([4,9,16.])
print(arr3)
arr3.dtype

[ 4.  9. 16.]


dtype('float64')

Operamos sobre el array como si fuera un simple numero

In [24]:
print(arr1 + 1)
print(arr1)

[[2 3 4]
 [5 6 7]]
[[1 2 3]
 [4 5 6]]


In [25]:
print(arr1 * 10)

[[10 20 30]
 [40 50 60]]


In [27]:
print(arr1 @ arr2)

[150 360]


## Universal Functions (ufunc)

In [33]:
print(np.sqrt(arr3))
print(np.sqrt(arr4))

[2. 3. 4.]
[4.47213595 5.47722558 6.32455532 7.07106781]


In [30]:
print(arr3.sum())
print(arr1.sum(axis=0))
print(arr1.sum())

29.0
[5 7 9]
21


## Selectores

Obtiene un subconjunto del arreglo, incluyendo la pocision inicial excluyendo la final

In [39]:
print(arr3[0:2])
print(arr1[:,:2])
print(arr4[2:])

[4. 9.]
[[1 2]
 [4 5]]
[40 50]


## Constructores

In [ ]:
Crea un array con elementos dentro del rango 0 a n, creciendo de a 1

In [45]:
arr5 = np.arange(1*6)
arr7 = np.arange(10)
print(arr5)
print(arr7)

[0 1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
reshape() nos permite reorganizar un array, el primer parametro es la cantidad de filas y el segundo las columnas

In [44]:
arr6 = np.arange(2*5).reshape(2,5)
print(arr6)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Views

Los subarrays creados con selectores funcionan a traves de referencias hacia el array original, toda modificacion hecha al subarray se vera reflejada en la original

In [52]:
arr8 = np.array([[11,22,33],[44,55,66]])
sarr = arr8[:, :2]
print(sarr)
sarr[0,0] = 99
print(sarr)
print(arr8)

[[11 22]
 [44 55]]
[[99 22]
 [44 55]]
[[99 22 33]
 [44 55 66]]
